# Лабораторная работа №3: Создание и обработка собственных исключений

## Цель работы

Изучить механизм создания и обработки собственных исключений в Java. Научиться:

- Определять собственный класс исключения.
- Генерировать исключения с помощью `throw` и объявлять их через `throws`.
- Обрабатывать исключения с помощью `try-catch`.

## Задача

Реализовать программу, которая считывает с консоли 10 чисел и заполняет ими массив размером 10, добиваясь, чтобы в массиве оказались только чётные числа. При вводе нечётного числа программа должна:

1. Сгенерировать собственное исключение.
2. Перехватить и обработать его, уведомив пользователя об ошибочном вводе.
3. Запросить повторный ввод на том же месте массива.

## Реализация

### Класс собственного исключения
```java
// Исключение для нечётных чисел
public class EvenNumberException extends Exception {
    public EvenNumberException(String message) {
        super(message);
    }
}
```

### Метод генерации исключения
```java
/**
 * Добавляет число в массив, если оно чётное.
 * @throws EvenNumberException если число нечетное.
 */
public static void addNumber(int number, int[] array, int index) throws EvenNumberException {
    if (number % 2 != 0) {
        throw new EvenNumberException("Нечетное число: " + number + ". Ожидалось четное.");
    }
    array[index] = number;
}
```

### Главный метод
```java
public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    int[] numbers = new int[10];
    int count = 0;

    System.out.println("Введите 10 четных чисел:");
    while (count < numbers.length) {
        System.out.print("Число " + (count + 1) + ": ");
        int input;
        try {
            input = Integer.parseInt(scanner.nextLine());
        } catch (NumberFormatException e) {
            System.out.println("Ошибка: введите корректное целое число.");
            continue;
        }

        try {
            addNumber(input, numbers, count);
            count++;
        } catch (EvenNumberException e) {
            System.out.println("Ошибка: " + e.getMessage());
            System.out.println("Попробуйте еще раз.");
        }
    }

    System.out.println("Массив четных чисел заполнен:");
    for (int num : numbers) {
        System.out.print(num + " ");
    }
    scanner.close();
}
```

## Пример работы
```
Введите 10 четных чисел:
Число 1: 5
Ошибка: Нечетное число: 5. Ожидалось четное.
Попробуйте еще раз.
Число 1: 4
Число 2: 7
Ошибка: Нечетное число: 7. Ожидалось четное.
Попробуйте еще раз.
Число 2: 2
...
Массив четных чисел заполнен:
4 2 6 8 10 12 14 16 18 20 
```

## Вывод

В ходе выполнения лабораторной работы была изучена техника разработки собственных исключений в Java. Получен практический опыт:

- Определения и использования пользовательских классов исключений.
- Генерации исключений при некорректных входных данных.
- Обработки исключений с помощью `try-catch` и организации повторного ввода.

Программа успешно проверяет ввод на чётность и обеспечивает заполнение массива только корректными значениями.
